### ISSUE TITLE
No Servers Listed

### ISSUE THREAD

**Issue by NataIynn** [darkfoxdeveloper/ConquerLoader#2]
Hi, im trying to use this loader, but no servers being listed. Using the main branch. But if I use the download version 1.0.0.5, it'll show just fine.

**Comment by darkfoxdeveloper** [comment]
I'm glad you're using the Loader, the problem you mention may be related to the configuration structure changes that have occurred for the next v1.0.0.6 that hasn't come out yet, try making the configuration from scratch and tell me if it continues the problem

**Comment by NataIynn** [comment]
Yeah, I did this without a config, and made one from scratch, but still happened. Another bug possible I've found. Is this supported on windows 10? I've tried it on 2 different window 10 pcs, and seems like its not bypassing properly.

On my windows 11 pc, it works fine. I am using 6371 client.

**Comment by darkfoxdeveloper** [comment]
> Yeah, I did this without a config, and made one from scratch, but still happened. Another bug possible I've found. Is this supported on windows 10? I've tried it on 2 different window 10 pcs, and seems like its not bypassing properly.
> 
> On my windows 11 pc, it works fine. I am using 6371 client.

You can do a video for see the problem? Can’t reproduce it in my pc. Yes it works in Windows 10 only need .Net Framework 4.6 and C++ redistributable 2019. Test with Release version.

**Comment by NataIynn** [comment]
Okay yeah, I just needed C++ redistributable 2019, now it works on my window 10 pcs. I'll make a video shortly for the development branch.

Edit: The release version,  keeps resetting the resolution scaling, I've noticed. This may be fixed in your newest version, but hard to tell since no servers listed.  This happens on my windows 10 pc, and my main windows 11 pc.

Edit2: I also tried the development branch loader, and seems to be working properly on my laptop. I'll have to give it a try again on my main pc. However the  resolution does still get reset for some reason. I've been using smartconquerloader and that doesn't have that issue.

**Comment by darkfoxdeveloper** [comment]
You can send me your config file for test?

**Comment by NataIynn** [comment]
Wouldn't let me upload as ".json", but this is the file.

[config.txt](https://github.com/darkfoxdeveloper/ConquerLoader/files/10984697/config.txt)

**Comment by darkfoxdeveloper** [comment]
> Wouldn't let me upload as ".json", but this is the file.
> 
> [config.txt](https://github.com/darkfoxdeveloper/ConquerLoader/files/10984697/config.txt)

Can try with the new beta? https://github.com/darkfoxdeveloper/ConquerLoader/releases/download/v1.0.0.6/ConquerLoaderV1.0.0.6Beta.zip Can disable now the screen changes with this option: 
![image](https://user-images.githubusercontent.com/46323771/226169659-4a9e186e-d7b0-4baf-86aa-b7310dd7b943.png)

**Comment by NataIynn** [comment]
Server list still invisible for some odd reason.

Edit: So for the server list, I tried using it on another client thats version 6325, and server list shows fine. But on my 6372 client, the server list is invisible. The 6325 client is also in my program files x86, while the 6372 client is on my desktop.

![image](https://user-images.githubusercontent.com/28743579/227321045-08415660-0c6b-439b-9230-14a24670cff7.png)

**Comment by darkfoxdeveloper** [comment]
> 

If you can give me the client can test if are a specific problem with the version 6372 and thanks for your responses, the idea is that the loader is compatible with all these versions but it may happen that there are some where there are problems
